### PR TITLE
Correct grammar mistakes

### LINKED ISSUE #27: Mistakes in grammar

### PR DESCRIPTION
**Pull request by isaacknjama**
FIxes #27

### CODE REVIEW

**Comment by isaacknjama** [comment]
`03-DebasementRisk.md`, the statement `In effect this means you can set a higher threshold of trust for users to redeem the on-chain bitcoin form the mint. This protects users` seems to be incomplete.

**Comment by isaacknjama** [comment]
`03-DebasementRisk.md`, the statement `Using these two data points they could estimate the likelihood of debasement if the level of redemptions to the mint causes the can raise alarm on increased redemptions of honest` doesn't seem to convey meaningful information to anyone reading it.

**Comment by isaacknjama** [comment]
Referring to `LN Gateway`, is it more appropriate to phrase it as `a LN Gateway` or `an LN Gateway`? Consider the fact that reference is being made to the gateway.

**Review by humansinstitute — APPROVED** [review]
Looks good.

**Pull request merged**
